import { CombatExtraSpellAction, CombatUnitClass, ICombatUnit, LogEvent } from '@wowarenalogs/parser';

import { getEnglishSpellName } from '../data/spellEffectData';
import { ccSpellIds, disarmSpellIds, rootSpellIds, spells } from '../data/spellTags';
import trinketItemIdsData from '../data/trinketItemIds.json';
import { fmtTime, isHealerSpec, specToString } from './cooldowns';
import { computeIncomingDR, IDRInfo } from './drAnalysis';
import { distanceBetween, getUnitPositionAtTime, hasLineOfSight } from './losAnalysis';

// ---------------------------------------------------------------------------
// Constants
// ---------------------------------------------------------------------------

/** Gladiator's Medallion — active PvP trinket that breaks CC */
const GLADIATOR_TRINKET_SPELL_ID = '336126';
/** Adaptation — passive auto-break trinket (proc spell) */
const ADAPTATION_TRINKET_SPELL_ID = '195756';

/** Item IDs for Relentless (passive DR, no active) — generated by start:generateTrinketItemIds */
const RELENTLESS_ITEM_IDS = new Set<string>(trinketItemIdsData.relentlessItemIds);
/** Item IDs for Adaptation (auto-break on 5s CC, no manual cast) — generated by start:generateTrinketItemIds */
const ADAPTATION_ITEM_IDS = new Set<string>(trinketItemIdsData.adaptationItemIds);

const HEALER_TRINKET_CD_S = 90;
const DPS_TRINKET_CD_S = 120;

/**
 * Window in ms within which a trinket cast is considered a direct response
 * to a CC application (applied then trinket used within this window).
 */
const TRINKET_RESPONSE_WINDOW_MS = 5000;

/**
 * Minimum damage taken during a CC window for it to be considered a meaningful
 * missed trinket opportunity.
 */
const SIGNIFICANT_CC_DAMAGE = 30_000;

/**
 * Buffs/abilities that can cause a targeted CC cast to whiff (dodge, reflect, immunity,
 * untargetable). Maps the buff's spell ID → display name shown as the avoidance reason.
 * Seasonal maintenance: update IDs here when these abilities change.
 */
const CC_AVOIDANCE_BUFF_SPELLS = new Map<string, string>([
  // NOTE: Fade (586) itself is excluded — it only drops threat, no CC immunity. BUT the Phase Shift
  // PvP talent (408557) makes Fade phase the priest out (untargetable ~1s), applying aura 408558 —
  // which IS a real CC-avoidance window. 408558 only exists when the talent is taken, so listing the
  // aura is self-gating (no pvpTalents check needed). B139-P0.
  ['408558', 'Phase Shift'],
  ['1246965', 'Psychic Shroud'],
  ['377362', 'Precognition'],
  ['378464', 'Nullifying Shroud'],
  ['23920', 'Spell Reflection'],
  ['354610', 'Glimpse'],
  ['227847', 'Bladestorm'],
  ['389774', 'Bladestorm'],
  ['642', 'Divine Shield'],
  ['1022', 'Blessing of Protection'],
  ['204018', 'Blessing of Spellwarding'],
  ['45438', 'Ice Block'],
  ['186265', 'Aspect of the Turtle'],
  ['48707', 'Anti-Magic Shell'],
]);

const DRUID_FORM_BUFFS = new Map<string, string>([
  ['5487', 'Bear Form'],
  ['768', 'Cat Form'],
  ['783', 'Travel Form'],
  ['24858', 'Moonkin Form'],
  ['114223', 'Tree of Life'],
]);

const BREAKABLE_CC_SPELL_IDS = new Set([
  '118', // Polymorph
  '51514', // Hex
  '3355', // Freezing Trap
  '5782', // Fear
  '8122', // Psychic Scream
  '19386', // Wyvern Sting
  '20066', // Repentance
]);

/** Shaman Grounding Totem — redirects the first targeted hostile spell. */
const GROUNDING_TOTEM_SPELL_ID = '8177';

/** Priest Shadow Word: Death — can break a freshly-applied breakable CC on the caster. */
const SHADOW_WORD_DEATH_SPELL_ID = '32379';

const GROUND_CC_SPELL_IDS = new Set<string>([
  '3355', // Freezing Trap (Hunter)
  '207684', // Sigil of Misery (Demon Hunter)
  '202137', // Sigil of Silence (Demon Hunter)
  '192058', // Capacitor Totem (Shaman)
  '30283', // Shadowfury (Warlock)
  '113724', // Ring of Frost (Mage)
]);

const REPOSITIONING_SPELL_IDS = new Map<string, string>([
  ['119996', 'Transcendence: Transfer'],
  ['109132', 'Roll'],
  ['115008', 'Chi Torpedo'],
  ['116841', "Tiger's Lust"],
  ['102401', 'Wild Charge'],
  ['1850', 'Dash'],
  ['106898', 'Stampeding Roar'],
  ['190784', 'Divine Steed'],
  ['1044', 'Blessing of Freedom'],
  ['58875', 'Spirit Walk'],
  ['192082', 'Gust of Wind'],
  ['192077', 'Wind Rush Totem'],
  ['2645', 'Ghost Wolf'],
  ['358267', 'Hover'],
  ['370665', 'Rescue'],
  ['121536', "Angel's Feather"],
  ['58984', 'Shadowmeld'],
  ['5487', 'Bear Form'],
  ['768', 'Cat Form'],
  ['783', 'Travel Form'],
  ['24858', 'Moonkin Form'],
]);

const TARGETED_CC_DODGE_SPELLS = new Set<string>([
  '119996', // Transcendence: Transfer
  '58984', // Shadowmeld
]);

const TREMOR_BREAKABLE_CC_IDS = new Set<string>([
  '5782', // Fear
  '8122', // Psychic Scream
  '5484', // Howl of Terror
]);

// ---------------------------------------------------------------------------
// Interfaces
// ---------------------------------------------------------------------------

export type TrinketType = 'Gladiator' | 'Adaptation' | 'Relentless' | 'Unknown';

export interface ICCInstance {
  atSeconds: number;
  durationSeconds: number;
  spellId: string;
  spellName: string;
  sourceName: string;
  sourceSpec: string;
  damageTakenDuring: number;
  trinketState: 'used' | 'available_unused' | 'on_cooldown' | 'passive_trinket';
  /** Seconds until trinket is ready again. Only populated when trinketState === 'on_cooldown'. */
  trinketCDSecondsLeft?: number;
  /** DR state at the time this CC was applied. null if spell not in DR category map. */
  drInfo: IDRInfo | null;
  /**
   * Distance in yards between caster and target at the moment of CC application.
   * null when advanced logging is absent.
   */
  distanceYards: number | null;
  /**
   * Whether the caster had unobstructed line of sight to the target.
   * null when arena geometry is not mapped or advanced logging is absent.
   */
  losBlocked: boolean | null;
}

export interface IRootInstance {
  atSeconds: number;
  durationSeconds: number;
  spellId: string;
  spellName: string;
  sourceName: string;
  sourceSpec: string;
}

export interface IInterruptInstance {
  atSeconds: number;
  lockoutDurationSeconds: number;
  kickSpellId: string;
  kickSpellName: string;
  interruptedSpellId: string;
  interruptedSpellName: string;
  sourceName: string;
  sourceSpec: string;
}

export interface ICCAvoidedInstance {
  atSeconds: number;
  spellId: string;
  spellName: string;
  avoidanceSpellName: string;
  avoidanceSpellId: string;
  sourceName: string;
  sourceSpec: string;
}

export interface IPlayerCCTrinketSummary {
  playerName: string;
  playerSpec: string;
  trinketType: TrinketType;
  trinketCooldownSeconds: number;
  ccInstances: ICCInstance[];
  trinketUseTimes: number[]; // atSeconds for each trinket cast
  /** CC windows where trinket was available but player didn't use it, with significant damage */
  missedTrinketWindows: ICCInstance[];
  /** Roots applied by enemies. No DR category. */
  rootInstances: IRootInstance[];
  /** Disarms applied by enemies. No DR category. */
  disarmInstances: IRootInstance[];
  /** Kicks (interrupts) landed by enemies. */
  interruptInstances: IInterruptInstance[];
  /** CC avoidance/mitigation/breaks. Always populated by analyzePlayerCCAndTrinket
   * (empty array when none) — part of the summary contract. */
  ccAvoidedInstances: ICCAvoidedInstance[];
}

// ---------------------------------------------------------------------------
// Helpers
// ---------------------------------------------------------------------------

export function detectTrinketType(unit: ICombatUnit): TrinketType {
  const trinketSlots = (unit.info?.equipment ?? []).filter((_, i) => [12, 13].includes(i));
  if (trinketSlots.some((e) => RELENTLESS_ITEM_IDS.has(e.id))) return 'Relentless';
  if (trinketSlots.some((e) => ADAPTATION_ITEM_IDS.has(e.id))) return 'Adaptation';
  if (trinketSlots.length > 0) return 'Gladiator';
  return 'Unknown';
}

/**
 * Returns all timestamps (ms) at which the unit successfully cast their active trinket.
 */
function getTrinketCastTimestamps(unit: ICombatUnit, trinketType: TrinketType): number[] {
  if (trinketType === 'Relentless') return []; // passive, never cast
  const spellId = trinketType === 'Adaptation' ? ADAPTATION_TRINKET_SPELL_ID : GLADIATOR_TRINKET_SPELL_ID;
  return unit.spellCastEvents
    .filter((e) => e.logLine.event === LogEvent.SPELL_CAST_SUCCESS && e.spellId === spellId)
    .map((e) => e.logLine.timestamp);
}

/**
 * Given a sorted list of trinket cast timestamps, returns whether the trinket
 * was off cooldown at `atMs`.
 */
function isTrinketAvailable(castTimestamps: number[], cooldownMs: number, atMs: number): boolean {
  // Find the last cast before atMs
  let lastCast = -Infinity;
  for (const ts of castTimestamps) {
    if (ts <= atMs) lastCast = ts;
    else break;
  }
  if (lastCast === -Infinity) return true; // never used → available
  return atMs - lastCast >= cooldownMs;
}

// ---------------------------------------------------------------------------
// Main analysis
// ---------------------------------------------------------------------------

export function analyzePlayerCCAndTrinket(
  player: ICombatUnit,
  enemies: ICombatUnit[],
  combat: { startTime: number; endTime: number; startInfo: { zoneId: string } },
): IPlayerCCTrinketSummary {
  const enemyIds = new Set(enemies.map((u) => u.id));
  const matchStartMs = combat.startTime;

  const trinketType = detectTrinketType(player);
  const isHealer = isHealerSpec(player.spec);
  const trinketCooldownSeconds = isHealer ? HEALER_TRINKET_CD_S : DPS_TRINKET_CD_S;
  const trinketCooldownMs = trinketCooldownSeconds * 1000;

  const trinketCastTimestamps = getTrinketCastTimestamps(player, trinketType).sort((a, b) => a - b);

  // Build a map of CC apply → remove timestamps for this player from enemies
  // spellId → list of { applyMs, removeMs }
  const ccWindows: Array<{
    spellId: string;
    spellName: string;
    srcName: string;
    srcUnitId: string;
    applyMs: number;
    removeMs: number;
  }> = [];

  const pendingCC = new Map<string, { applyMs: number; spellName: string; srcName: string; srcUnitId: string }>();

  const pendingRoot = new Map<string, { applyMs: number; spellName: string; srcId: string; srcName: string }>();
  const rootWindows: Array<{
    spellId: string;
    spellName: string;
    srcId: string;
    srcName: string;
    applyMs: number;
    removeMs: number;
  }> = [];

  const pendingDisarm = new Map<string, { applyMs: number; spellName: string; srcId: string; srcName: string }>();
  const disarmWindows: Array<{
    spellId: string;
    spellName: string;
    srcId: string;
    srcName: string;
    applyMs: number;
    removeMs: number;
  }> = [];

  for (const aura of player.auraEvents) {
    const spellId = aura.spellId;
    if (!spellId) continue;
    if (!enemyIds.has(aura.srcUnitId)) continue;

    if (rootSpellIds.has(spellId) || disarmSpellIds.has(spellId)) {
      const isRoot = rootSpellIds.has(spellId);
      const pending = isRoot ? pendingRoot : pendingDisarm;
      const windows = isRoot ? rootWindows : disarmWindows;
      const key = `${spellId}:${aura.srcUnitId}`;
      const event = aura.logLine.event;

      if (event === LogEvent.SPELL_AURA_APPLIED) {
        pending.set(key, {
          applyMs: aura.timestamp,
          spellName: getEnglishSpellName(spellId, aura.spellName),
          srcId: aura.srcUnitId,
          srcName: aura.srcUnitName,
        });
      } else if (
        event === LogEvent.SPELL_AURA_REMOVED ||
        event === LogEvent.SPELL_AURA_BROKEN ||
        event === LogEvent.SPELL_AURA_BROKEN_SPELL
      ) {
        const p = pending.get(key);
        if (p) {
          windows.push({
            spellId,
            spellName: p.spellName,
            srcId: p.srcId,
            srcName: p.srcName,
            applyMs: p.applyMs,
            removeMs: aura.timestamp,
          });
          pending.delete(key);
        }
      }
    }

    const isBacklashPossible = spellId === '196363' || spellId === '34914';
    if (!ccSpellIds.has(spellId) && !isBacklashPossible) continue;

    // FIX 2: key by spellId+caster so re-applications from the same caster don't
    // overwrite the pending entry before the first removal fires.
    const ccKey = `${spellId}:${aura.srcUnitId}`;
    const event = aura.logLine.event;
    if (event === LogEvent.SPELL_AURA_APPLIED) {
      pendingCC.set(ccKey, {
        applyMs: aura.timestamp,
        spellName: getEnglishSpellName(spellId, aura.spellName),
        srcName: aura.srcUnitName,
        srcUnitId: aura.srcUnitId,
      });
    } else if (
      event === LogEvent.SPELL_AURA_REMOVED ||
      event === LogEvent.SPELL_AURA_BROKEN ||
      event === LogEvent.SPELL_AURA_BROKEN_SPELL
    ) {
      const pending = pendingCC.get(ccKey);
      if (pending) {
        ccWindows.push({
          spellId,
          spellName: pending.spellName,
          srcName: pending.srcName,
          srcUnitId: pending.srcUnitId,
          applyMs: pending.applyMs,
          removeMs: aura.timestamp,
        });
        pendingCC.delete(ccKey);
      }
    }
  }

  // Close any CCs still pending at match end
  Array.from(pendingCC.entries()).forEach(([ccKey, pending]) => {
    const [pendingSpellId] = ccKey.split(':');
    ccWindows.push({
      spellId: pendingSpellId,
      spellName: pending.spellName,
      srcName: pending.srcName,
      srcUnitId: pending.srcUnitId,
      applyMs: pending.applyMs,
      removeMs: combat.endTime,
    });
  });

  for (const [key, p] of pendingRoot) {
    const [pendingSpellId] = key.split(':');
    rootWindows.push({
      spellId: pendingSpellId,
      spellName: p.spellName,
      srcId: p.srcId,
      srcName: p.srcName,
      applyMs: p.applyMs,
      removeMs: combat.endTime,
    });
  }
  for (const [key, p] of pendingDisarm) {
    const [pendingSpellId] = key.split(':');
    disarmWindows.push({
      spellId: pendingSpellId,
      spellName: p.spellName,
      srcId: p.srcId,
      srcName: p.srcName,
      applyMs: p.applyMs,
      removeMs: combat.endTime,
    });
  }

  // Resolve source spec from enemies list
  const enemySpecMap = new Map(enemies.map((u) => [u.id, specToString(u.spec)]));
  const enemyUnitMap = new Map(enemies.map((u) => [u.id, u]));
  const zoneId = combat.startInfo.zoneId;

  // Build ICCInstance list (without drInfo — computed after sort)
  const filteredCCWindows = ccWindows.filter((w) => {
    if (w.spellId === '34914') {
      const durationS = (w.removeMs - w.applyMs) / 1000;
      return durationS <= 4; // Horror is 3s; DoT is 21s
    }
    return true;
  });

  // B111: bind each trinket cast to the SINGLE CC it actually broke, instead of tagging
  // every CC that landed within 5s of the cast. An active PvP trinket (Gladiator's Medallion
  // / Adaptation) removes loss-of-control, so it can only break a CC that was still ACTIVE at
  // the cast instant (applyMs ≤ castTs ≤ removeMs). The old window mis-tagged CCs that had
  // already expired before the trinket press, so the coach blamed a trivial / DR'd-to-0 CC
  // rather than the real one. When several CCs are active at once, credit the longest-active.
  const TRINKET_BREAK_TOLERANCE_MS = 250;
  const trinketBrokenWindowIdx = new Set<number>();
  for (const trinketTs of trinketCastTimestamps) {
    let primaryIdx = -1;
    let primaryDurationMs = -1;
    filteredCCWindows.forEach((w, idx) => {
      const activeAtCast =
        trinketTs >= w.applyMs - TRINKET_BREAK_TOLERANCE_MS && trinketTs <= w.removeMs + TRINKET_BREAK_TOLERANCE_MS;
      if (!activeAtCast) return;
      const durationMs = w.removeMs - w.applyMs;
      if (durationMs > primaryDurationMs) {
        primaryDurationMs = durationMs;
        primaryIdx = idx;
      }
    });
    if (primaryIdx >= 0) trinketBrokenWindowIdx.add(primaryIdx);
  }

  const ccInstancesUnsorted: Omit<ICCInstance, 'drInfo'>[] = filteredCCWindows.map((w, idx) => {
    const damageTakenDuring = player.damageIn
      .filter((d) => enemyIds.has(d.srcUnitId) && d.logLine.timestamp >= w.applyMs && d.logLine.timestamp <= w.removeMs)
      .reduce((sum, d) => sum + Math.abs(d.effectiveAmount), 0);

    let trinketState: ICCInstance['trinketState'];
    let trinketCDSecondsLeft: number | undefined;
    if (trinketType === 'Relentless') {
      trinketState = 'passive_trinket';
    } else if (trinketBrokenWindowIdx.has(idx)) {
      trinketState = 'used';
    } else if (isTrinketAvailable(trinketCastTimestamps, trinketCooldownMs, w.applyMs)) {
      trinketState = 'available_unused';
    } else {
      trinketState = 'on_cooldown';
      let lastCast = -Infinity;
      for (const ts of trinketCastTimestamps) {
        if (ts <= w.applyMs) lastCast = ts;
        else break;
      }
      if (lastCast !== -Infinity) {
        const remainingMs = trinketCooldownMs - (w.applyMs - lastCast);
        trinketCDSecondsLeft = Math.ceil(remainingMs / 1000);
      }
    }

    // LoS + distance at CC application time
    const casterUnit = enemyUnitMap.get(w.srcUnitId);
    const casterPos = casterUnit ? getUnitPositionAtTime(casterUnit, w.applyMs) : null;
    const targetPos = getUnitPositionAtTime(player, w.applyMs);

    const distanceYards = casterPos && targetPos ? Math.round(distanceBetween(casterPos, targetPos) * 10) / 10 : null;

    const losBlocked =
      casterPos && targetPos
        ? (() => {
            const los = hasLineOfSight(zoneId, casterPos, targetPos);
            return los === null ? null : !los;
          })()
        : null;

    return {
      atSeconds: (w.applyMs - matchStartMs) / 1000,
      durationSeconds: (w.removeMs - w.applyMs) / 1000,
      spellId: w.spellId,
      spellName: w.spellName,
      sourceName: w.srcName,
      sourceSpec: enemySpecMap.get(w.srcUnitId) ?? 'Unknown',
      damageTakenDuring,
      trinketState,
      trinketCDSecondsLeft,
      distanceYards,
      losBlocked,
    };
  });

  const sorted = [...ccInstancesUnsorted].sort((a, b) => a.atSeconds - b.atSeconds);
  const drAnnotations = computeIncomingDR(sorted, matchStartMs);
  const ccInstances: ICCInstance[] = sorted.map((cc, i) => ({ ...cc, drInfo: drAnnotations[i] ?? null }));

  const missedTrinketWindows = ccInstances.filter(
    (c) => c.trinketState === 'available_unused' && c.damageTakenDuring >= SIGNIFICANT_CC_DAMAGE,
  );

  const rootInstances: IRootInstance[] = rootWindows
    .map((w) => ({
      atSeconds: (w.applyMs - matchStartMs) / 1000,
      durationSeconds: (w.removeMs - w.applyMs) / 1000,
      spellId: w.spellId,
      spellName: w.spellName,
      sourceName: w.srcName,
      sourceSpec: enemySpecMap.get(w.srcId) ?? 'Unknown',
    }))
    .sort((a, b) => a.atSeconds - b.atSeconds);

  const disarmInstances: IRootInstance[] = disarmWindows
    .map((w) => ({
      atSeconds: (w.applyMs - matchStartMs) / 1000,
      durationSeconds: (w.removeMs - w.applyMs) / 1000,
      spellId: w.spellId,
      spellName: w.spellName,
      sourceName: w.srcName,
      sourceSpec: enemySpecMap.get(w.srcId) ?? 'Unknown',
    }))
    .sort((a, b) => a.atSeconds - b.atSeconds);

  const interruptInstances: IInterruptInstance[] = [];
  for (const action of player.actionIn) {
    if (action.logLine.event !== LogEvent.SPELL_INTERRUPT) continue;
    if (!enemyIds.has(action.srcUnitId)) continue;
    const extraAction = action as unknown as CombatExtraSpellAction;
    const kickSpellId = extraAction.extraSpellId;
    const lockoutDurationSeconds = spells[kickSpellId]?.duration ?? 3;
    interruptInstances.push({
      atSeconds: (action.timestamp - matchStartMs) / 1000,
      lockoutDurationSeconds,
      kickSpellId,
      kickSpellName: getEnglishSpellName(kickSpellId, extraAction.extraSpellName),
      interruptedSpellId: action.spellId ?? '',
      interruptedSpellName: getEnglishSpellName(action.spellId ?? '', action.spellName),
      sourceName: action.srcUnitName,
      sourceSpec: enemySpecMap.get(action.srcUnitId) ?? 'Unknown',
    });
  }
  interruptInstances.sort((a, b) => a.atSeconds - b.atSeconds);

  // ─── CC Avoidance Correlation Logic ───────────────────────────────────────
  const ccAvoidedInstances: ICCAvoidedInstance[] = [];

  // Track active buff intervals on the player
  const activeBuffs: Array<{ spellId: string; name: string; applyMs: number; removeMs: number }> = [];
  const pendingBuffs = new Map<string, { applyMs: number; name: string }>();

  if (player.info?.interestingAurasJSON) {
    try {
      const initialAuras = JSON.parse(player.info.interestingAurasJSON);
      if (Array.isArray(initialAuras)) {
        for (const auraId of initialAuras) {
          const spellIdStr = String(auraId);
          if (CC_AVOIDANCE_BUFF_SPELLS.has(spellIdStr)) {
            pendingBuffs.set(spellIdStr, {
              applyMs: combat.startTime,
              name: CC_AVOIDANCE_BUFF_SPELLS.get(spellIdStr) ?? '',
            });
          } else if (DRUID_FORM_BUFFS.has(spellIdStr)) {
            pendingBuffs.set(spellIdStr, {
              applyMs: combat.startTime,
              name: DRUID_FORM_BUFFS.get(spellIdStr) ?? '',
            });
          }
        }
      }
    } catch (e) {
      // Ignore parse errors
    }
  }

  for (const aura of player.auraEvents) {
    const spellId = aura.spellId;
    if (!spellId || (!CC_AVOIDANCE_BUFF_SPELLS.has(spellId) && !DRUID_FORM_BUFFS.has(spellId))) continue;

    const event = aura.logLine.event;
    if (event === LogEvent.SPELL_AURA_APPLIED || event === LogEvent.SPELL_AURA_REFRESH) {
      const pending = pendingBuffs.get(spellId);
      if (pending) {
        activeBuffs.push({
          spellId,
          name: pending.name,
          applyMs: pending.applyMs,
          removeMs: aura.timestamp,
        });
      }
      pendingBuffs.set(spellId, {
        applyMs: aura.timestamp,
        name: CC_AVOIDANCE_BUFF_SPELLS.get(spellId) ?? DRUID_FORM_BUFFS.get(spellId) ?? '',
      });
    } else if (event === LogEvent.SPELL_AURA_REMOVED) {
      const pending = pendingBuffs.get(spellId);
      if (pending) {
        activeBuffs.push({
          spellId,
          name: pending.name,
          applyMs: pending.applyMs,
          removeMs: aura.timestamp,
        });
        pendingBuffs.delete(spellId);
      }
    }
  }

  for (const [spellId, pending] of pendingBuffs.entries()) {
    activeBuffs.push({
      spellId,
      name: pending.name,
      applyMs: pending.applyMs,
      removeMs: combat.endTime,
    });
  }

  // 1. Unified Buff & Mobility CC Avoidance (targeted and ground CCs)
  for (const enemy of enemies) {
    for (const cast of enemy.spellCastEvents) {
      if (cast.logLine.event !== LogEvent.SPELL_CAST_SUCCESS) continue;
      if (!cast.spellId || (!ccSpellIds.has(cast.spellId) && !GROUND_CC_SPELL_IDS.has(cast.spellId))) continue;

      const isTargeted = cast.destUnitId === player.id || cast.destUnitName === player.name;
      const isGroundCC = GROUND_CC_SPELL_IDS.has(cast.spellId);

      if (isTargeted || isGroundCC) {
        const castTimeMs = cast.logLine.timestamp;
        const gotCCd = ccInstances.some(
          (cc) => Math.abs(cc.atSeconds * 1000 - (castTimeMs - matchStartMs)) <= 1500 && cc.spellId === cast.spellId,
        );

        if (!gotCCd) {
          // A. Buff-Based Avoidance
          const activeBuff = activeBuffs.find((b) => castTimeMs >= b.applyMs && castTimeMs <= b.removeMs);
          if (activeBuff) {
            const ccSpellName = getEnglishSpellName(cast.spellId, cast.spellName);
            const isDruidForm = DRUID_FORM_BUFFS.has(activeBuff.spellId);
            const isPolymorphOrHex =
              ccSpellName.toLowerCase().includes('polymorph') || ccSpellName.toLowerCase().includes('hex');

            if (!isDruidForm || isPolymorphOrHex) {
              ccAvoidedInstances.push({
                atSeconds: (castTimeMs - matchStartMs) / 1000,
                spellId: cast.spellId,
                spellName: ccSpellName,
                avoidanceSpellName: activeBuff.name,
                avoidanceSpellId: activeBuff.spellId,
                sourceName: enemy.name,
                sourceSpec: enemySpecMap.get(enemy.id) ?? 'Unknown',
              });
              continue; // Avoid double counting
            }
          }

          // B. Mobility-Based Avoidance
          const mobilityCast = player.spellCastEvents.find(
            (e) =>
              e.logLine.event === LogEvent.SPELL_CAST_SUCCESS &&
              e.spellId &&
              REPOSITIONING_SPELL_IDS.has(e.spellId) &&
              Math.abs(e.logLine.timestamp - castTimeMs) <= 1500,
          );
          if (mobilityCast && mobilityCast.spellId) {
            // H14: Shapeshifting (DRUID_FORM_BUFFS) does NOT reposition the player out of a
            // ground AoE stun, so a Druid form cast must never be credited with dodging a
            // ground CC. Apply the same gate the buff branch uses: forms only break
            // Polymorph/Hex, never ground CCs.
            const isDruidForm = DRUID_FORM_BUFFS.has(mobilityCast.spellId);
            const canDodge = !isDruidForm && (isGroundCC || TARGETED_CC_DODGE_SPELLS.has(mobilityCast.spellId));
            if (canDodge) {
              ccAvoidedInstances.push({
                atSeconds: (castTimeMs - matchStartMs) / 1000,
                spellId: cast.spellId,
                spellName: getEnglishSpellName(cast.spellId, cast.spellName),
                avoidanceSpellName: REPOSITIONING_SPELL_IDS.get(mobilityCast.spellId) ?? '',
                avoidanceSpellId: mobilityCast.spellId,
                sourceName: enemy.name,
                sourceSpec: enemySpecMap.get(enemy.id) ?? 'Unknown',
              });
            }
          }
        }
      }
    }
  }

  // 2. Grounding Totem Redirects (only tracked on Shaman players to avoid multi-teammate duplication)
  if (player.class === CombatUnitClass.Shaman) {
    for (const enemy of enemies) {
      for (const cast of enemy.spellCastEvents) {
        if (cast.logLine.event !== LogEvent.SPELL_CAST_SUCCESS) continue;
        if (!cast.spellId || !ccSpellIds.has(cast.spellId)) continue;

        const isGroundingTotem =
          cast.destUnitName?.toLowerCase().includes('grounding totem') ||
          (cast.destUnitId?.startsWith('Creature-') && cast.destUnitId.split('-')[5] === '5925');
        if (isGroundingTotem) {
          const castTimeMs = cast.logLine.timestamp;
          ccAvoidedInstances.push({
            atSeconds: (castTimeMs - matchStartMs) / 1000,
            spellId: cast.spellId,
            spellName: getEnglishSpellName(cast.spellId, cast.spellName),
            avoidanceSpellName: 'Grounding Totem',
            avoidanceSpellId: GROUNDING_TOTEM_SPELL_ID,
            sourceName: enemy.name,
            sourceSpec: enemySpecMap.get(enemy.id) ?? 'Unknown',
          });
        }
      }
    }
  }

  // 4. Paladin Blessing of Sacrifice Breaks
  if (player.class === CombatUnitClass.Paladin) {
    for (const cc of ccInstances) {
      const ccAppliedTimeMs = cc.atSeconds * 1000 + matchStartMs;
      if (BREAKABLE_CC_SPELL_IDS.has(cc.spellId) && cc.durationSeconds <= 4.0) {
        const sacrificeCast = player.spellCastEvents.find(
          (e) =>
            (e.spellId === '6940' || e.spellId === '199448') &&
            e.logLine.event === LogEvent.SPELL_CAST_SUCCESS &&
            ccAppliedTimeMs >= e.logLine.timestamp &&
            ccAppliedTimeMs - e.logLine.timestamp <= 12000,
        );
        if (sacrificeCast) {
          ccAvoidedInstances.push({
            atSeconds: cc.atSeconds,
            spellId: cc.spellId,
            spellName: cc.spellName,
            avoidanceSpellName: 'Blessing of Sacrifice',
            avoidanceSpellId: sacrificeCast.spellId || '6940',
            sourceName: cc.sourceName,
            sourceSpec: cc.sourceSpec,
          });
        }
      }
    }
  }

  // 5. Shadow Word: Death Breaks (only Priest players)
  if (player.class === CombatUnitClass.Priest) {
    for (const cc of ccInstances) {
      const ccAppliedTimeMs = cc.atSeconds * 1000 + matchStartMs;
      if (BREAKABLE_CC_SPELL_IDS.has(cc.spellId) && cc.durationSeconds <= 1.0) {
        const swdCast = player.spellCastEvents.find(
          (e) =>
            e.spellId === SHADOW_WORD_DEATH_SPELL_ID &&
            e.logLine.event === LogEvent.SPELL_CAST_SUCCESS &&
            e.logLine.timestamp >= ccAppliedTimeMs - 500 &&
            e.logLine.timestamp <= ccAppliedTimeMs,
        );
        if (swdCast) {
          ccAvoidedInstances.push({
            atSeconds: cc.atSeconds,
            spellId: cc.spellId,
            spellName: cc.spellName,
            avoidanceSpellName: 'Shadow Word: Death',
            avoidanceSpellId: SHADOW_WORD_DEATH_SPELL_ID,
            sourceName: cc.sourceName,
            sourceSpec: cc.sourceSpec,
          });
        }
      }
    }
  }

  // 6. Tremor Totem Breaks (only Shaman players)
  if (player.class === CombatUnitClass.Shaman) {
    for (const cc of ccInstances) {
      const ccAppliedTimeMs = cc.atSeconds * 1000 + matchStartMs;
      if (TREMOR_BREAKABLE_CC_IDS.has(cc.spellId) && cc.durationSeconds <= 2.0) {
        const tremorCast = player.spellCastEvents.find(
          (e) =>
            e.spellId === '8143' &&
            e.logLine.event === LogEvent.SPELL_CAST_SUCCESS &&
            ccAppliedTimeMs >= e.logLine.timestamp &&
            ccAppliedTimeMs - e.logLine.timestamp <= 10000,
        );
        if (tremorCast) {
          ccAvoidedInstances.push({
            atSeconds: cc.atSeconds,
            spellId: cc.spellId,
            spellName: cc.spellName,
            avoidanceSpellName: 'Tremor Totem',
            avoidanceSpellId: '8143',
            sourceName: cc.sourceName,
            sourceSpec: cc.sourceSpec,
          });
        }
      }
    }
  }

  ccAvoidedInstances.sort((a, b) => a.atSeconds - b.atSeconds);

  return {
    playerName: player.name,
    playerSpec: specToString(player.spec),
    trinketType,
    trinketCooldownSeconds,
    ccInstances,
    trinketUseTimes: trinketCastTimestamps.map((ts) => (ts - matchStartMs) / 1000),
    missedTrinketWindows,
    rootInstances,
    disarmInstances,
    interruptInstances,
    ccAvoidedInstances,
  };
}

// ---------------------------------------------------------------------------
// Formatter
// ---------------------------------------------------------------------------

export function formatCCTrinketForContext(summaries: IPlayerCCTrinketSummary[]): string[] {
  const lines: string[] = [];
  lines.push('CC RECEIVED BY YOUR TEAM (enemies CCing you) + TRINKET USAGE:');

  const hasCCData = summaries.some((s) => s.ccInstances.length > 0);
  if (!hasCCData) {
    lines.push('  No hard CC events detected on your team.');
    return lines;
  }

  for (const s of summaries) {
    if (s.ccInstances.length === 0) continue;

    // Aggregate CC counts by type
    const countBySpell = new Map<string, number>();
    let immuneOrReducedCount = 0;
    let meleeCCCount = 0;
    const missedTrinketCount = s.missedTrinketWindows.length;

    for (const cc of s.ccInstances) {
      countBySpell.set(cc.spellName, (countBySpell.get(cc.spellName) ?? 0) + 1);
      if (cc.drInfo && cc.drInfo.level !== 'Full') immuneOrReducedCount++;
      if (cc.distanceYards !== null && cc.distanceYards <= 8 && cc.losBlocked !== true) meleeCCCount++;
    }

    const ccBreakdown = [...countBySpell.entries()]
      .sort((a, b) => b[1] - a[1])
      .map(([name, count]) => `${count}× ${name}`)
      .join(', ');
    const trinketCdStr =
      s.trinketType === 'Relentless' || s.trinketType === 'Unknown' ? s.trinketType : `${s.trinketType} trinket`;

    const notes: string[] = [];
    if (immuneOrReducedCount > 0) notes.push(`${immuneOrReducedCount} reduced/immune DR`);
    if (meleeCCCount > 0) notes.push(`${meleeCCCount} at melee range`);
    if (missedTrinketCount > 0) {
      const totalDmg = s.missedTrinketWindows.reduce((sum, w) => sum + w.damageTakenDuring, 0);
      notes.push(`⚠ ${missedTrinketCount} missed trinket window(s) (${Math.round(totalDmg / 1000)}k dmg total)`);
    }
    const noteStr = notes.length > 0 ? ` [${notes.join('; ')}]` : '';

    // Trinket use times outside CC windows
    const trinketResponseWindowS = TRINKET_RESPONSE_WINDOW_MS / 1000;
    const offCCUses = s.trinketUseTimes.filter(
      (t) => !s.ccInstances.some((cc) => Math.abs(cc.atSeconds - t) <= trinketResponseWindowS),
    );
    const trinketStr =
      offCCUses.length > 0 ? `${trinketCdStr} used off-CC at ${offCCUses.map(fmtTime).join(', ')}` : trinketCdStr;

    lines.push(
      `  ${s.playerSpec} (${s.playerName}): ${s.ccInstances.length} CC — ${ccBreakdown} | ${trinketStr}${noteStr}`,
    );
  }

  return lines;
}
