export const DISPEL_FEATURE_FLAGS = {
  F18_FATAL_DISPEL: true,
  F124_ENHANCED_CC_ANNOTATIONS: true,
  F131_F132_CLEANSE_COOLDOWNS: true,
  F142_OFFENSIVE_DISPEL_SUMMARY: true,
  F152_MISSED_PURGES_TIMELINE: true,
};
